### ISSUE TITLE
Some question about data process

### ISSUE THREAD

**Issue by Yangr116** [zhengye1995/kesci-2021-underwater-optics#2]
您好，有个问题想要请教一下。您在README里面说加入了“无目标图”来训练，但是我在您的数据转换文件中并没有无目标图的处理（/tools/process_data/xmltococo.py）。想问下无目标图在annotation文件中应该如何体现呢？
祝您生活愉快！

**Comment by zhengye1995** [comment]
你好，无目标图在label文件中就是 只有images 字段中的相应图片，但是在annotations字段中没有对应的内容

**Comment by Yangr116** [comment]
十分感谢!



---Original---
From: ***@***.***&gt;
Date: Sun, Aug 8, 2021 12:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zhengye1995/kesci-2021-underwater-optics] Some question about data process (#2)




 
你好，无目标图在label文件中就是 只有images 字段中的相应图片，但是在annotations字段中没有对应的内容
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
