### ISSUE TITLE
Is it possible to share the dataset, thanks a lot?

### ISSUE THREAD

**Issue by junyongyou** [zhengye1995/kesci-2021-underwater-optics#4]
Hi, I know the contest has already finished and the organizer has closed the dataset. I am just wondering if it is possible that you still have the dataset and can share with me? I am working on a similar project. Thank you so much.

**Comment by zhengye1995** [comment]
Please provide your email for sending the dataset.

**Comment by junyongyou** [comment]
Thanks a lot. My email is junyong.you@gmail.com.

**Comment by OutBreak-hui** [comment]
Can you copy me that email as well? Thank you so much,My email is 1039807929@qq.com

**Comment by xiaobai-lkk** [comment]
您好，可以发送一份数据集吗？非常感谢，我的邮箱是1960380001@qq.com,感谢感谢

**Comment by xiaobai-lkk** [comment]
Hello, can you send a data set?  Thank you very much. My email is 1960380001@qq.com. Thank you

**Comment by zhengye1995** [comment]
> Can you copy me that email as well? Thank you so much,My email is [1039807929@qq.com](mailto:1039807929@qq.com)

已发

**Comment by zhengye1995** [comment]
> 您好，可以发送一份数据集吗？非常感谢，我的邮箱是[1960380001@qq.com](mailto:1960380001@qq.com),感谢感谢

已发

**Comment by murdonson** [comment]
你好 可以发一下数据集吗 我的邮箱是328859599@qq.com
