### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by DUT-fx** [zhengye1995/kesci-2021-underwater-optics#6]
![image](https://user-images.githubusercontent.com/109496574/179698368-f1ac7e28-90bc-4c0e-a07a-f4b91e39f5f5.png)
求教为什么会出现out of memory，为啥pytorch会占用那么多的G，导致只有100多M可用。我看它的work_dirs的log有这个问题
![image](https://user-images.githubusercontent.com/109496574/179698665-f0ac656f-cc25-41e9-85eb-f0e4fef0b10e.png)
这是由于作者的代码原因引起的吗？还是我哪里出现了问题？求赐教

**Comment by zhengye1995** [comment]
In this repo, I used Nvidia 3090 GPU which has 24GB memory. The backbone and neck model used in this repo is  DetectoRS which needs a large GPU memory in training. If your GPU do not have enough memory, you can try use a smaller scale for training or use other detection models, such as the new sota convnext or swin transformer, etc.
