### ISSUE TITLE
About the environment configuration and the work_dirs/log

### ISSUE THREAD

**Issue by DUT-fx** [zhengye1995/kesci-2021-underwater-optics#7]
I wanna know if your environment configuration has something wrong because I set the environment as you give but failed. Can you give me the Version of CUDA,pytorch,mmcv-full again? look forward to your reply so much and thanks for your kind help!

**Comment by zhengye1995** [comment]
Pleaser refer my [README.md](https://github.com/zhengye1995/kesci-2021-underwater-optics#readme), all the information you need is there.

**Comment by zhengye1995** [comment]
If you use the new version mmdetection, you just need to follow the environment configuration for the official description of mmdetection .

**Comment by zhengye1995** [comment]
If you use the new version mmdetection, you just need to follow the environment configuration for the official description of mmdetection .
